let entries=JSON.parse(localStorage.getItem("uds_v2_entries")||"[]"),actions=JSON.parse(localStorage.getItem("uds_v2_actions")||"[]");
window.onload=()=>{document.querySelectorAll("nav button[data-tab]").forEach(btn=>btn.addEventListener("click",()=>showTab(btn.dataset.tab)));document.querySelectorAll("button[data-go]").forEach(btn=>btn.addEventListener("click",()=>showTab(btn.dataset.go)));const n=new Date(),t=n.toISOString().split("T")[0];date.value=t;reportDate.value=t;time.value=n.toTimeString().slice(0,5);renderAll();checkSupabase();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js?v=2.1")};
function supabaseReady(){return typeof SUPABASE_URL==='string'&&SUPABASE_URL.includes("supabase.co")&&typeof SUPABASE_ANON_KEY==='string'&&SUPABASE_ANON_KEY.length>20}
function headers(extra={}){return{"apikey":SUPABASE_ANON_KEY,"Authorization":"Bearer "+SUPABASE_ANON_KEY,"Content-Type":"application/json",...extra}}
function checkSupabase(){syncStatus.textContent=supabaseReady()?"v2.1 • online sync configured":"v2.1 • offline mode only";supabaseStatus.textContent=supabaseReady()?`Connected: ${SUPABASE_URL}`:"Not connected. Add publishable/anon key to config.js."}
function showTab(id){document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));document.getElementById(id).classList.add("active");const nav=document.querySelector(`nav button[data-tab='${id}']`);if(nav)nav.classList.add("active");window.scrollTo(0,0)}
photos.addEventListener("change",async()=>{photoPreview.innerHTML="";for(const f of [...photos.files]){const d=await fileToData(f);photoPreview.innerHTML+=`<img src="${d}">`}});
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=e=>res(e.target.result);r.onerror=rej;r.readAsDataURL(file)})}
function dataUrlToBlob(d){const a=d.split(","),m=a[0].match(/:(.*?);/)[1],b=atob(a[1]);let n=b.length,u8=new Uint8Array(n);while(n--)u8[n]=b.charCodeAt(n);return new Blob([u8],{type:m})}
async function saveEntry(){const ps=[];for(const f of [...photos.files])ps.push(await fileToData(f));const e={local_id:"e_"+Date.now(),cloud_id:null,date:val("date"),time:val("time"),shift:val("shift"),heading:val("heading"),levelArea:val("levelArea"),crew:val("crew"),supervisor:val("supervisor"),foreman:val("foreman"),personnel:num("personnel"),activity:val("activity"),roundChainage:val("roundChainage"),metresAdvanced:num("metresAdvanced"),boltsInstalled:num("boltsInstalled"),cableBolts:num("cableBolts"),meshInstalled:val("meshInstalled"),shotcreteM3:num("shotcreteM3"),shotcreteThickness:val("shotcreteThickness"),equipment:val("equipment"),groundCondition:val("groundCondition"),delayType:val("delayType"),delayHours:num("delayHours"),job:val("job"),delays:val("delays"),nextShift:val("nextShift"),safetyObservation:val("safetyObservation"),goodCatch:val("goodCatch"),notes:val("notes"),checks:{ptha:chk("ptha"),lif:chk("lif"),scaled:chk("scaled"),groundSupport:chk("groundSupport"),boltPattern:chk("boltPattern"),shotcreteQuality:chk("shotcreteQuality"),ventilation:chk("ventilation"),servicesClear:chk("servicesClear"),barricades:chk("barricades"),reentry:chk("reentry")},photos:ps,synced:false,createdAt:new Date().toISOString()};if(!e.heading||!e.job){alert("Add Heading / Drive and Job Being Performed.");return}entries.unshift(e);saveLocal();clearEntry();renderAll();if(supabaseReady()&&navigator.onLine)await syncAll();else alert("Saved offline.")}
function saveAction(){const a={local_id:"a_"+Date.now(),cloud_id:null,heading:val("actionHeading"),actionText:val("actionText"),owner:val("owner"),priority:val("priority"),dueDate:val("dueDate"),status:val("status"),synced:false,createdAt:new Date().toISOString()};if(!a.actionText){alert("Enter the action required.");return}actions.unshift(a);saveLocal();clearAction();renderAll();if(supabaseReady()&&navigator.onLine)syncAll();else alert("Action saved offline.")}
async function syncAll(){if(!supabaseReady()){alert("Supabase key is not configured yet.");return}if(!navigator.onLine){alert("No internet.");return}syncStatus.textContent="Syncing...";try{for(const e of entries.filter(x=>!x.synced))await syncEntry(e);for(const a of actions.filter(x=>!x.synced))await syncAction(a);saveLocal();renderAll();syncStatus.textContent="Sync complete";alert("Sync complete.")}catch(err){console.error(err);syncStatus.textContent="Sync failed";alert("Sync failed: "+err.message)}}
async function syncEntry(e){const body={entry_date:e.date,entry_time:e.time,shift:e.shift,heading:e.heading,level_area:e.levelArea,activity:e.activity,round_chainage:e.roundChainage,metres_advanced:e.metresAdvanced,bolts_installed:e.boltsInstalled,mesh_installed:e.meshInstalled,shotcrete_m3:e.shotcreteM3,shotcrete_thickness:e.shotcreteThickness,equipment:e.equipment,ground_condition:e.groundCondition,job:e.job,delays:e.delays,next_shift:e.nextShift,notes:extraNotes(e),ptha:e.checks.ptha,lif:e.checks.lif,scaled:e.checks.scaled,ground_support:e.checks.groundSupport,bolt_pattern:e.checks.boltPattern,shotcrete_quality:e.checks.shotcreteQuality,ventilation:e.checks.ventilation,services_clear:e.checks.servicesClear,barricades:e.checks.barricades,reentry:e.checks.reentry,synced_by:"UDS Development Log v2.1"};const r=await fetch(`${SUPABASE_URL}/rest/v1/development_entries`,{method:"POST",headers:headers({"Prefer":"return=representation"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());const s=(await r.json())[0];e.cloud_id=s.id;for(let i=0;i<(e.photos||[]).length;i++){const u=await uploadPhoto(e.photos[i],s.id,i);await insertPhoto(s.id,u)}e.synced=true}
function extraNotes(e){return `Crew: ${e.crew||""}; Supervisor: ${e.supervisor||""}; Foreman: ${e.foreman||""}; Personnel: ${e.personnel||0}; Cable bolts: ${e.cableBolts||0}; Delay type: ${e.delayType||""}; Delay hours: ${e.delayHours||0}; Safety observation: ${e.safetyObservation||""}; Good catch: ${e.goodCatch||""}; Notes: ${e.notes||""}`}
async function uploadPhoto(d,id,i){const blob=dataUrlToBlob(d),path=`${id}/${Date.now()}_${i}.jpg`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${PHOTO_BUCKET}/${path}`,{method:"POST",headers:{"apikey":SUPABASE_ANON_KEY,"Authorization":"Bearer "+SUPABASE_ANON_KEY,"Content-Type":blob.type,"x-upsert":"true"},body:blob});if(!r.ok)throw new Error(await r.text());return `${SUPABASE_URL}/storage/v1/object/public/${PHOTO_BUCKET}/${path}`}
async function insertPhoto(id,u){const r=await fetch(`${SUPABASE_URL}/rest/v1/development_photos`,{method:"POST",headers:headers(),body:JSON.stringify({development_entry_id:id,photo_url:u,caption:""})});if(!r.ok)throw new Error(await r.text())}
async function syncAction(a){const body={heading:a.heading,priority:a.priority,action_text:a.actionText,owner:a.owner,due_date:a.dueDate||null,status:a.status};const r=await fetch(`${SUPABASE_URL}/rest/v1/development_actions`,{method:"POST",headers:headers({"Prefer":"return=representation"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());a.cloud_id=(await r.json())[0].id;a.synced=true}
async function loadCloudCount(){if(!supabaseReady()){alert("Supabase key is not configured yet.");return}try{const r=await fetch(`${SUPABASE_URL}/rest/v1/development_entries?select=id`,{headers:headers()});if(!r.ok)throw new Error(await r.text());alert(`Cloud has ${(await r.json()).length} development entries.`)}catch(e){alert("Could not check cloud: "+e.message)}}
function renderAll(){renderDashboard();renderActions();checkSupabase()}
function renderDashboard(){const today=new Date().toISOString().split("T")[0],todays=entries.filter(e=>e.date===today),open=actions.filter(a=>a.status!=="Closed");tileHeadings.textContent=todays.length;tileMetres.textContent=sum(todays,"metresAdvanced").toFixed(1);tileBolts.textContent=sum(todays,"boltsInstalled");tileShotcrete.textContent=sum(todays,"shotcreteM3").toFixed(1);tileActions.textContent=open.length;tileSafety.textContent=todays.filter(e=>(e.safetyObservation||"").trim()).length;recentLogs.innerHTML=entries.slice(0,5).map(logCard).join("")}
function logCard(e){return `<div class="item"><strong>${esc(e.heading)}</strong><span class="badge">${esc(e.shift)}</span><span class="badge">${esc(e.activity)}</span><span class="badge ${e.synced?'synced':'unsynced'}">${e.synced?'Synced':'Offline'}</span><br>${esc(e.date)} ${esc(e.time)}<p><b>Crew:</b> ${esc(e.crew)} | <b>Supervisor:</b> ${esc(e.supervisor)}</p><p><b>Job:</b> ${esc(e.job)}</p><p><b>Progress:</b> ${e.metresAdvanced||0}m | ${e.boltsInstalled||0} bolts | ${e.cableBolts||0} cable bolts | ${e.shotcreteM3||0}m³ shotcrete</p><p><b>Delay:</b> ${esc(e.delayType)} ${e.delayHours?`(${e.delayHours} hrs)`:""}</p><p><b>Next:</b> ${esc(e.nextShift)}</p><div class="photos">${(e.photos||[]).map(p=>`<img src="${p}">`).join("")}</div></div>`}
function renderActions(){actionList.innerHTML=actions.map(a=>`<div class="item"><strong>${esc(a.priority)}: ${esc(a.actionText)}</strong><span class="badge ${a.synced?'synced':'unsynced'}">${a.synced?'Synced':'Offline'}</span><br>Heading: ${esc(a.heading)}<br>Owner: ${esc(a.owner)}<br>Due: ${esc(a.dueDate)} | Status: ${esc(a.status)}</div>`).join("")}
function generateReport(){const d=val("reportDate"),todays=entries.filter(e=>e.date===d),open=actions.filter(a=>a.status!=="Closed"),m=sum(todays,"metresAdvanced"),b=sum(todays,"boltsInstalled"),cb=sum(todays,"cableBolts"),sc=sum(todays,"shotcreteM3"),delay=sum(todays,"delayHours"),safety=todays.filter(e=>(e.safetyObservation||"").trim());let h=`<h2>UDS Daily Development Report</h2><p><b>Date:</b> ${esc(d)}</p><p>The shift recorded ${todays.length} active development heading(s), ${m.toFixed(1)} metre(s) advanced, ${b} bolt(s), ${cb} cable bolt(s), and ${sc.toFixed(1)} m³ of shotcrete. Total reported delay time was ${delay.toFixed(1)} hour(s), with ${open.length} open action(s).</p><div class="summary"><div><b>Headings</b><br>${todays.length}</div><div><b>Metres</b><br>${m.toFixed(1)}</div><div><b>Bolts</b><br>${b}</div><div><b>Cable Bolts</b><br>${cb}</div><div><b>Shotcrete</b><br>${sc.toFixed(1)} m³</div><div><b>Delay Hours</b><br>${delay.toFixed(1)}</div><div><b>Safety Obs.</b><br>${safety.length}</div><div><b>Open Actions</b><br>${open.length}</div></div><hr>`;if(!todays.length)h+="<p>No entries recorded for this date.</p>";todays.forEach(e=>h+=`<h3>${esc(e.heading)}</h3><p><b>Shift:</b> ${esc(e.shift)} | <b>Activity:</b> ${esc(e.activity)}</p><p><b>Crew:</b> ${esc(e.crew)} | <b>Supervisor:</b> ${esc(e.supervisor)} | <b>Foreman:</b> ${esc(e.foreman)} | <b>Personnel:</b> ${e.personnel||0}</p><p><b>Progress:</b> ${e.metresAdvanced||0}m | ${e.boltsInstalled||0} bolts | ${e.cableBolts||0} cable bolts | Mesh: ${esc(e.meshInstalled)} | Shotcrete: ${e.shotcreteM3||0}m³ @ ${esc(e.shotcreteThickness)}</p><p><b>Equipment:</b> ${esc(e.equipment)}</p><p><b>Ground:</b> ${esc(e.groundCondition)}</p><p><b>Job:</b> ${esc(e.job)}</p><p><b>Delay:</b> ${esc(e.delayType)} ${e.delayHours?`(${e.delayHours} hrs)`:""} - ${esc(e.delays)}</p><p><b>Safety / Quality:</b> ${controlText(e.checks)}</p><p><b>Safety Observation:</b> ${esc(e.safetyObservation)}</p><p><b>Good Catch:</b> ${esc(e.goodCatch)}</p><p><b>Next Shift:</b> ${esc(e.nextShift)}</p><div class="photos">${(e.photos||[]).map(p=>`<img src="${p}">`).join("")}</div><hr>`);h+="<h3>Open Actions</h3>";if(!open.length)h+="<p>No open actions.</p>";open.forEach(a=>h+=`<p><b>${esc(a.priority)}</b>: ${esc(a.actionText)}<br>Heading: ${esc(a.heading)} | Owner: ${esc(a.owner)} | Due: ${esc(a.dueDate)} | Status: ${esc(a.status)}</p>`);reportOutput.innerHTML=h}
function exportActions(){const rows=[["Priority","Heading","Action","Owner","Due Date","Status"],...actions.map(a=>[a.priority,a.heading,a.actionText,a.owner,a.dueDate,a.status])],csv=rows.map(r=>r.map(x=>`"${String(x||"").replaceAll('"','""')}"`).join(",")).join("\n");download("UDS_Development_Action_Register.csv",csv,"text/csv")}
function exportBackup(){download("UDS_Development_Log_Backup.json",JSON.stringify({entries,actions},null,2),"application/json")}
function clearLocalData(){if(!confirm("Clear all local app data?"))return;entries=[];actions=[];saveLocal();renderAll()}
function saveLocal(){localStorage.setItem("uds_v2_entries",JSON.stringify(entries));localStorage.setItem("uds_v2_actions",JSON.stringify(actions))}
function download(n,c,t){const b=new Blob([c],{type:t}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
function controlText(c={}){const l={ptha:"PTHA",lif:"LIF",scaled:"Scaling Complete",groundSupport:"Ground Support Complete",boltPattern:"Bolt Pattern Verified",shotcreteQuality:"Shotcrete Quality Checked",ventilation:"Ventilation Adequate",servicesClear:"Services Clear",barricades:"Barricades/Controls",reentry:"Re-entry Confirmed"};return Object.keys(l).filter(k=>c[k]).map(k=>l[k]).join(", ")||"Not recorded"}
function clearEntry(){["heading","levelArea","crew","supervisor","foreman","personnel","roundChainage","metresAdvanced","boltsInstalled","cableBolts","meshInstalled","shotcreteM3","shotcreteThickness","equipment","delayHours","job","delays","nextShift","safetyObservation","goodCatch","notes"].forEach(id=>document.getElementById(id).value="");["ptha","lif","scaled","groundSupport","boltPattern","shotcreteQuality","ventilation","servicesClear","barricades","reentry"].forEach(id=>document.getElementById(id).checked=false);photos.value="";photoPreview.innerHTML=""}
function clearAction(){["actionHeading","actionText","owner","dueDate"].forEach(id=>document.getElementById(id).value="")}
function val(id){return document.getElementById(id).value}function chk(id){return document.getElementById(id).checked}function num(id){return Number(document.getElementById(id).value||0)}function sum(arr,key){return arr.reduce((s,e)=>s+(Number(e[key])||0),0)}function esc(x){return String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}